// Passkey Authentication Tests
// Comprehensive test suite for Stellar Protocol 21+ Passkey support

#[cfg(test)]
mod tests {
    use super::*;
    use soroban_sdk::{
        contract, contractimpl, Address, Env, Symbol, Bytes, BytesN,
        testutils::{Address as TestAddress, AuthorizedFunction, Auth, AuthorizedInvocation},
        crypto::secp256r1_verify,
    };

    // Mock contract for testing passkey functionality
    #[contract]
    pub struct PasskeyTestContract;

    #[contractimpl]
    impl PasskeyTestContract {
        pub fn test_register_passkey(
            env: Env,
            user: Address,
            public_key: BytesN<33>,
            credential_id: Bytes,
            origin: Symbol,
        ) -> Result<(), u32> {
            crate::SoroSusuTrait::register_passkey(
                env,
                user,
                public_key,
                credential_id,
                origin,
            )
        }

        pub fn test_authenticate_with_passkey(
            env: Env,
            user: Address,
            signature: crate::passkey_auth::PasskeySignature,
            credential_id: Bytes,
        ) -> Result<bool, u32> {
            crate::SoroSusuTrait::authenticate_with_passkey(
                env,
                user,
                signature,
                credential_id,
            )
        }

        pub fn test_generate_challenge(env: Env, user: Address) -> Bytes {
            crate::SoroSusuTrait::generate_challenge(env, user)
        }

        pub fn test_get_auth_profile(
            env: Env,
            user: Address,
        ) -> Result<crate::passkey_auth::UserAuthProfile, u32> {
            crate::SoroSusuTrait::get_auth_profile(env, user)
        }

        pub fn test_set_preferred_auth_method(
            env: Env,
            user: Address,
            method: crate::passkey_auth::AuthMethod,
        ) -> Result<(), u32> {
            crate::SoroSusuTrait::set_preferred_auth_method(env, user, method)
        }
    }

    #[test]
    fn test_passkey_registration() {
        let env = Env::default();
        let admin = Address::generate(&env);
        let user = Address::generate(&env);

        // Initialize contract
        crate::SoroSusuTrait::init(env.clone(), admin.clone());

        // Generate test passkey data
        let public_key = BytesN::from_array(&env, &[0x02; 33]); // Mock secp256r1 public key
        let credential_id = Bytes::from_slice(&env, &[0x01, 0x02, 0x03, 0x04]);
        let origin = Symbol::new(&env, "https://sorosusu.app");

        // Register passkey
        env.mock_all_auths();
        let result = PasskeyTestContract::test_register_passkey(
            env.clone(),
            user.clone(),
            public_key,
            credential_id.clone(),
            origin,
        );

        assert!(result.is_ok(), "Passkey registration should succeed");

        // Verify the credential was stored
        let profile = PasskeyTestContract::test_get_auth_profile(env.clone(), user.clone())
            .unwrap();
        assert_eq!(profile.passkey_credentials.len(), 1);
        assert_eq!(profile.preferred_method, crate::passkey_auth::AuthMethod::Secp256r1);
    }

    #[test]
    fn test_passkey_authentication_flow() {
        let env = Env::default();
        let admin = Address::generate(&env);
        let user = Address::generate(&env);

        // Initialize contract
        crate::SoroSusuTrait::init(env.clone(), admin.clone());

        // Register a passkey first
        let public_key = BytesN::from_array(&env, &[0x02; 33]);
        let credential_id = Bytes::from_slice(&env, &[0x01, 0x02, 0x03, 0x04]);
        let origin = Symbol::new(&env, "https://sorosusu.app");

        env.mock_all_auths();
        PasskeyTestContract::test_register_passkey(
            env.clone(),
            user.clone(),
            public_key,
            credential_id.clone(),
            origin,
        ).unwrap();

        // Generate a challenge
        let challenge = PasskeyTestContract::test_generate_challenge(env.clone(), user.clone());
        assert!(!challenge.is_empty(), "Challenge should not be empty");

        // Create a mock signature (in real implementation, this would be generated by WebAuthn)
        let signature = crate::passkey_auth::PasskeySignature {
            signature: BytesN::from_array(&env, &[0x01; 64]),
            auth_data: Bytes::from_slice(&env, &[0x05, 0x06]),
            client_data: Bytes::from_slice(&env, &[0x07, 0x08]),
        };

        // Test authentication (will fail with mock data but should exercise the flow)
        let result = PasskeyTestContract::test_authenticate_with_passkey(
            env.clone(),
            user.clone(),
            signature,
            credential_id,
        );

        // Expected to fail with mock data, but should not panic
        assert!(result.is_err(), "Mock authentication should fail gracefully");
        assert_eq!(result.unwrap_err(), crate::passkey_auth::PasskeyError::InvalidSignature as u32);
    }

    #[test]
    fn test_multiple_passkey_credentials() {
        let env = Env::default();
        let admin = Address::generate(&env);
        let user = Address::generate(&env);

        // Initialize contract
        crate::SoroSusuTrait::init(env.clone(), admin.clone());

        let origin = Symbol::new(&env, "https://sorosusu.app");

        // Register first passkey
        env.mock_all_auths();
        let public_key1 = BytesN::from_array(&env, &[0x02; 33]);
        let credential_id1 = Bytes::from_slice(&env, &[0x01, 0x02, 0x03, 0x04]);
        
        PasskeyTestContract::test_register_passkey(
            env.clone(),
            user.clone(),
            public_key1,
            credential_id1.clone(),
            origin,
        ).unwrap();

        // Register second passkey
        let public_key2 = BytesN::from_array(&env, &[0x03; 33]);
        let credential_id2 = Bytes::from_slice(&env, &[0x05, 0x06, 0x07, 0x08]);
        
        PasskeyTestContract::test_register_passkey(
            env.clone(),
            user.clone(),
            public_key2,
            credential_id2.clone(),
            origin,
        ).unwrap();

        // Verify both credentials are stored
        let profile = PasskeyTestContract::test_get_auth_profile(env.clone(), user.clone())
            .unwrap();
        assert_eq!(profile.passkey_credentials.len(), 2);

        // Try to register a third passkey (should succeed)
        let public_key3 = BytesN::from_array(&env, &[0x04; 33]);
        let credential_id3 = Bytes::from_slice(&env, &[0x09, 0x0A, 0x0B, 0x0C]);
        
        PasskeyTestContract::test_register_passkey(
            env.clone(),
            user.clone(),
            public_key3,
            credential_id3.clone(),
            origin,
        ).unwrap();

        // Verify all three credentials are stored
        let profile = PasskeyTestContract::test_get_auth_profile(env.clone(), user.clone())
            .unwrap();
        assert_eq!(profile.passkey_credentials.len(), 3);

        // Try to register a fourth passkey (should fail - max limit reached)
        let public_key4 = BytesN::from_array(&env, &[0x05; 33]);
        let credential_id4 = Bytes::from_slice(&env, &[0x0D, 0x0E, 0x0F, 0x10]);
        
        let result = PasskeyTestContract::test_register_passkey(
            env.clone(),
            user.clone(),
            public_key4,
            credential_id4,
            origin,
        );

        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), crate::passkey_auth::PasskeyError::TooManyCredentials as u32);
    }

    #[test]
    fn test_duplicate_credential_prevention() {
        let env = Env::default();
        let admin = Address::generate(&env);
        let user = Address::generate(&env);

        // Initialize contract
        crate::SoroSusuTrait::init(env.clone(), admin.clone());

        let public_key = BytesN::from_array(&env, &[0x02; 33]);
        let credential_id = Bytes::from_slice(&env, &[0x01, 0x02, 0x03, 0x04]);
        let origin = Symbol::new(&env, "https://sorosusu.app");

        // Register passkey first time
        env.mock_all_auths();
        PasskeyTestContract::test_register_passkey(
            env.clone(),
            user.clone(),
            public_key,
            credential_id.clone(),
            origin,
        ).unwrap();

        // Try to register the same credential again
        let public_key2 = BytesN::from_array(&env, &[0x03; 33]);
        let result = PasskeyTestContract::test_register_passkey(
            env.clone(),
            user.clone(),
            public_key2,
            credential_id,
            origin,
        );

        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), crate::passkey_auth::PasskeyError::InvalidCredential as u32);
    }

    #[test]
    fn test_auth_method_preference() {
        let env = Env::default();
        let admin = Address::generate(&env);
        let user = Address::generate(&env);

        // Initialize contract
        crate::SoroSusuTrait::init(env.clone(), admin.clone());

        // Initially should default to Ed25519
        let profile = PasskeyTestContract::test_get_auth_profile(env.clone(), user.clone());
        assert!(profile.is_err(), "No profile should exist initially");

        // Register a passkey
        let public_key = BytesN::from_array(&env, &[0x02; 33]);
        let credential_id = Bytes::from_slice(&env, &[0x01, 0x02, 0x03, 0x04]);
        let origin = Symbol::new(&env, "https://sorosusu.app");

        env.mock_all_auths();
        PasskeyTestContract::test_register_passkey(
            env.clone(),
            user.clone(),
            public_key,
            credential_id,
            origin,
        ).unwrap();

        // Should now default to Secp256r1
        let profile = PasskeyTestContract::test_get_auth_profile(env.clone(), user.clone())
            .unwrap();
        assert_eq!(profile.preferred_method, crate::passkey_auth::AuthMethod::Secp256r1);

        // Change preference back to Ed25519
        env.mock_all_auths();
        PasskeyTestContract::test_set_preferred_auth_method(
            env.clone(),
            user.clone(),
            crate::passkey_auth::AuthMethod::Ed25519,
        ).unwrap();

        // Verify preference changed
        let profile = PasskeyTestContract::test_get_auth_profile(env.clone(), user.clone())
            .unwrap();
        assert_eq!(profile.preferred_method, crate::passkey_auth::AuthMethod::Ed25519);
    }

    #[test]
    fn test_challenge_generation_and_expiry() {
        let env = Env::default();
        let admin = Address::generate(&env);
        let user = Address::generate(&env);

        // Initialize contract
        crate::SoroSusuTrait::init(env.clone(), admin.clone());

        // Generate challenge
        let challenge1 = PasskeyTestContract::test_generate_challenge(env.clone(), user.clone());
        let challenge2 = PasskeyTestContract::test_generate_challenge(env.clone(), user.clone());

        // Challenges should be different (due to timestamp and randomness)
        assert_ne!(challenge1, challenge2, "Challenges should be unique");

        // Test challenge verification (mock implementation)
        let is_valid = crate::passkey_auth::verify_challenge_valid(
            &env,
            &user,
            &challenge1,
        );
        assert!(is_valid.is_ok(), "Challenge should be valid immediately");
    }

    #[test]
    fn test_enhanced_auth_helper() {
        let env = Env::default();
        let admin = Address::generate(&env);
        let user = Address::generate(&env);

        // Initialize contract
        crate::SoroSusuTrait::init(env.clone(), admin.clone());

        // Test enhanced auth with no profile (should default to Ed25519)
        let result = crate::require_auth_enhanced(
            &env,
            &user,
            None,
            None,
            None,
        );
        assert!(result.is_ok(), "Enhanced auth should default to Ed25519");

        // Register a passkey
        let public_key = BytesN::from_array(&env, &[0x02; 33]);
        let credential_id = Bytes::from_slice(&env, &[0x01, 0x02, 0x03, 0x04]);
        let origin = Symbol::new(&env, "https://sorosusu.app");

        env.mock_all_auths();
        PasskeyTestContract::test_register_passkey(
            env.clone(),
            user.clone(),
            public_key,
            credential_id,
            origin,
        ).unwrap();

        // Test enhanced auth with explicit Ed25519 preference
        let result = crate::require_auth_enhanced(
            &env,
            &user,
            Some(crate::passkey_auth::AuthMethod::Ed25519),
            None,
            None,
        );
        assert!(result.is_ok(), "Should respect explicit Ed25519 preference");

        // Test enhanced auth with Secp256r1 but no signature (should fail)
        let result = crate::require_auth_enhanced(
            &env,
            &user,
            Some(crate::passkey_auth::AuthMethod::Secp256r1),
            None,
            None,
        );
        assert!(result.is_err(), "Should require passkey signature for Secp256r1");
    }

    #[test]
    fn test_profile_not_found_errors() {
        let env = Env::default();
        let admin = Address::generate(&env);
        let user = Address::generate(&env);

        // Initialize contract
        crate::SoroSusuTrait::init(env.clone(), admin.clone());

        // Try to get auth profile for user without profile
        let result = PasskeyTestContract::test_get_auth_profile(env.clone(), user.clone());
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), crate::passkey_auth::PasskeyError::ProfileNotFound as u32);

        // Try to set auth method for user without profile
        env.mock_all_auths();
        let result = PasskeyTestContract::test_set_preferred_auth_method(
            env.clone(),
            user.clone(),
            crate::passkey_auth::AuthMethod::Secp256r1,
        );
        assert!(result.is_err());
        assert_eq!(result.unwrap_err(), crate::passkey_auth::PasskeyError::ProfileNotFound as u32);
    }

    #[test]
    fn test_secp256r1_signature_verification() {
        let env = Env::default();
        
        // Generate a real secp256r1 key pair for testing
        let private_key = BytesN::from_array(&env, &[
            0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
            0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10,
            0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18,
            0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20,
        ]);
        
        let message = Bytes::from_slice(&env, b"test message");
        
        // Test that the secp256r1_verify function exists and can be called
        // (In a real test, you'd generate a proper signature)
        let public_key = BytesN::from_array(&env, &[0x02; 33]);
        let signature = BytesN::from_array(&env, &[0x01; 64]);
        
        // This will likely fail with mock data, but tests the function exists
        let result = secp256r1_verify(&env, &public_key, &signature, &message);
        
        // The function should execute without panicking (even if verification fails)
        let _ = result;
    }

    #[test]
    fn test_passkey_events() {
        let env = Env::default();
        let admin = Address::generate(&env);
        let user = Address::generate(&env);

        // Initialize contract
        crate::SoroSusuTrait::init(env.clone(), admin.clone());

        // Register a passkey and check for events
        let public_key = BytesN::from_array(&env, &[0x02; 33]);
        let credential_id = Bytes::from_slice(&env, &[0x01, 0x02, 0x03, 0x04]);
        let origin = Symbol::new(&env, "https://sorosusu.app");

        env.mock_all_auths();
        PasskeyTestContract::test_register_passkey(
            env.clone(),
            user.clone(),
            public_key,
            credential_id.clone(),
            origin,
        ).unwrap();

        // Check for registration event
        let events = env.events().all();
        assert!(events.len() > 0, "Should emit registration event");

        // Generate challenge and check for events
        PasskeyTestContract::test_generate_challenge(env.clone(), user.clone());
        
        let events_after_challenge = env.events().all();
        assert!(events_after_challenge.len() > events.len(), "Should emit challenge event");

        // Change auth method and check for events
        env.mock_all_auths();
        PasskeyTestContract::test_set_preferred_auth_method(
            env.clone(),
            user.clone(),
            crate::passkey_auth::AuthMethod::Ed25519,
        ).unwrap();

        let events_after_method_change = env.events().all();
        assert!(events_after_method_change.len() > events_after_challenge.len(), 
               "Should emit auth method change event");
    }
}
